apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: anand-test-backstage-sample-service
  description: Sample React web app
  labels:
    system: web-apps
  tags:
    - javascript
    - react
  links:
    - url: https://github.com/anand-tyagaraj/test-backstage-catalog
      title: Sample Service GitHub
      icon: code
  annotations:    
    github.com/project-slug: 'anand-tyagaraj/test-backstage-catalog'    
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: anand-tyagaraj
